"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my/our honor, Saul Marenco and Anthony Dezdha, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: Sm76875
UT EID 2: Ad54489
"""

# the constant used to calculate the step size
STEP_SIZE_CONSTANT = 3


# DO NOT modify this function.
def is_prime(n):
    """
    Determines if a number is prime.

    pre: n is a positive integer.
    post: Returns True if n is prime, otherwise returns False.
    """
    if n == 1:
        return False

    limit = int(n**0.5) + 1
    div = 2
    while div < limit:
        if n % div == 0:
            return False
        div += 1
    return True


# DO NOT modify this function.
def hash_word(s, size):
    """
    Hashes a lowercase string to an index in a hash table.

    pre: s is a lowercase string, and size is a positive integer representing either
         hash table size or the constant for double hashing.
    post: Returns an integer index in the range [0, size - 1] where the string hashes to.
    """
    hash_idx = 0
    for c in s:
        letter = ord(c) - 96
        hash_idx = (hash_idx * 26 + letter) % size
    return hash_idx


# TODO: Modify this function. You may delete this comment when you are done.
def step_size(s):
    """
    Calculates step size for double hashing using STEP_SIZE_CONSTANT.

    pre: s is a lowercase string.
    post: Returns the calculated step size as an integer based on the provided string.
    """
    key = hash_word(s, STEP_SIZE_CONSTANT)
    return STEP_SIZE_CONSTANT - (key % STEP_SIZE_CONSTANT)

# TODO: Modify this function. You may delete this comment when you are done.
def insert_word(s, hash_table):
    """
    Inserts a string into the hash table using double hashing for collision resolution.
    No duplicates are allowed.

    pre: s is a string, and hash_table is a list representing the hash table.
    post: Inserts s into hash_table at the correct index; resolves any collisions
          by double hashing.
    """
    key = hash_word(s, len(hash_table))
    step = step_size(s)
    while True :     
        if hash_table[key] == "":
            hash_table[key] = s
            return
        elif hash_table[key] == s:
            return
        key = (key + step) % len(hash_table)
        



# TODO: Modify this function. You may delete this comment when you are done.
def find_word(s, hash_table):
    """
    Searches for a string in the hash table.
    Note: using the `in` operator is incorrect as that will be O(N). We want
          an O(1) time average time complexity using hashing.

    pre: s is a string, and hash_table is a list representing the hash table.
    post: Returns True if s is found in hash_table, otherwise returns False.
    """
    key = hash_word(s, len(hash_table))
    if hash_table[key] == s:
        return True
    else:
        return s in hash_table

# TODO: Modify this function. You may delete this comment when you are done.
def is_reducible(s, hash_table, hash_memo):
    """
    Determines if a string is reducible using a recursive check.

    pre: s is a lowercase string, hash_table is a list representing the hash table,
         and hash_memo is a list representing the hash table
         for memoization.
    post: Returns True if s is reducible (also updates hash_memo by
          inserting s if reducible), otherwise returns False.
    """
    if find_word(s, hash_memo):
        return True
    
    if len(s) == 1:
        return s in {'a', 'i', 'o'}
    
    for i in range(len(s)):
        new_s = s[:i] + s[i+1:]
        if find_word(new_s, hash_table):
            if (is_reducible(new_s, hash_table, hash_memo)):
                insert_word(s, hash_memo)
                return True
    return False
    


# TODO: Modify this function. You may delete this comment when you are done.
def get_longest_words(string_list):
    """
    Finds longest words from a list.

    pre: string_list is a list of lowercase strings.
    post: Returns a list of words in string_list that have the maximum length.
    """
    if len(string_list) < 1:
        return []
    
    result = [string_list[0]]
    for i in range(1, len(string_list)):
        current = len(result[0])
        trying = len(string_list[i])
        if current == trying:
            result.append(string_list[i])
        elif trying > current:
            result = [string_list[i]]
    return result


